//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idare
    {
        public int IdareId { get; set; }
        public string IdariBirimAd { get; set; }
        public string IdariAd { get; set; }
    }
}
