//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mezunlar
    {
        public int MezunId { get; set; }
        public string MezunAd { get; set; }
        public string MezunSoyad { get; set; }
        public string MezunBolum { get; set; }
    }
}
