//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        public int YoneticiId { get; set; }
        public string YoneticiAd { get; set; }
        public string YoneticiSoyad { get; set; }
        public Nullable<bool> YoneticiRol { get; set; }
    }
}
